language: objective-c
osx_image: xcode9
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=IPAPI.xcworkspace
  - FRAMEWORK_SCHEME="IPAPI"
  matrix:
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="$FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="$FRAMEWORK_SCHEME" RUN_TESTS="NO"  POD_LINT="NO"

    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$FRAMEWORK_SCHEME"     RUN_TESTS="NO" POD_LINT="YES"
    - DESTINATION="OS=9.0,name=iPad 2"             SCHEME="$FRAMEWORK_SCHEME"     RUN_TESTS="NO" POD_LINT="NO"

    - DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="$FRAMEWORK_SCHEME"    RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$FRAMEWORK_SCHEME"    RUN_TESTS="NO" POD_LINT="NO"

    - DESTINATION="arch=x86_64"                    SCHEME="$FRAMEWORK_SCHEME"   RUN_TESTS="YES" POD_LINT="NO"
script:
  - set -o pipefail
  - git submodule update --init
  - xcodebuild -version

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
