language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=IPAPI.xcworkspace
  - IOS_FRAMEWORK_SCHEME="IPAPI iOS"
  - MACOS_FRAMEWORK_SCHEME="IPAPI macOS"
  - TVOS_FRAMEWORK_SCHEME="IPAPI tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="IPAPI watchOS"
script:
  - set -o pipefail
  - xcodebuild -version

  # Builds
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "platform=iOS Simulator,name=iPhone 6" build | xcpretty;
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$MACOS_FRAMEWORK_SCHEME" build | xcpretty;
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$TVOS_FRAMEWORK_SCHEME" -destination "platform=tvOS Simulator,name=Apple TV 1080p" build | xcpretty;
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$WATCHOS_FRAMEWORK_SCHEME" -destination "platform=watchOS Simulator,name=Apple Watch - 42mm" build | xcpretty;

  # Tests
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty;
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$MACOS_FRAMEWORK_SCHEME" build-for-testing test | xcpretty;
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$TVOS_FRAMEWORK_SCHEME" -destination "platform=tvOS Simulator,name=Apple TV 1080p" build-for-testing test | xcpretty;

  # Run `pod lib lint`
  - pod lib lint;
