language: objective-c
osx_image: xcode11.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - SCHEME="IPAPI"
  matrix:
    - DESTINATION="OS=4.0,name=Apple Watch Series 3 - 42mm" RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=3.2,name=Apple Watch - 42mm"          RUN_TESTS="NO"  POD_LINT="NO"

    - DESTINATION="OS=13.2,name=iPhone 11 Pro Max"          RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.3.1,name=iPad Air"                 RUN_TESTS="NO"  POD_LINT="NO"

    - DESTINATION="OS=13.2,name=Apple TV"                   RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"             RUN_TESTS="NO"  POD_LINT="NO"

    - DESTINATION="arch=x86_64"                             RUN_TESTS="YES" POD_LINT="NO"
script:
  - set -o pipefail
  - git submodule update --init
  - xcodebuild -version

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release GCC_GENERATE_TEST_COVERAGE_FILES=YES -enableCodeCoverage YES test | xcpretty;
    else
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release GCC_GENERATE_TEST_COVERAGE_FILES=YES -enableCodeCoverage YES test | xcpretty;
    else
      travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
